server:
  port: 8082  # on garde 8082 juste pour ce test

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cultureradar
    username: postgres
    password: "Admin2025!"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true

  flyway:
    enabled: false



