server:
  port: ${PORT:8082}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/cultureradar}
    username: ${DB_USER:postgres}
    password: "Admin2025!"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # en DEV, mets 'update' si besoin
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  flyway:
    enabled: true

# ==== Intégrations externes ====
openagenda:
  baseUrl: https://api.openagenda.com
  publicKey: ${OPENAGENDA_PUBLIC_KEY:${OPENAGENDA_API_KEY:}}
  agendaUid: ${OPENAGENDA_AGENDA_UID:56500817}

ga4:
  measurementId: ${GA4_MEASUREMENT_ID:}
  apiSecret: ${GA4_API_SECRET:}

unsplash:
  accessKey: ${UNSPLASH_ACCESS_KEY:}

# ==== Actuator (diagnostic) ====
management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      show-details: when_authorized

# ==== Logs utiles pour debug (optionnel) ====
logging:
  level:
    org.springframework.web: INFO
    org.springframework.web.client.RestTemplate: INFO
    org.springframework.http.client: INFO
    # com.cultureradar: DEBUG






