server:
  port: ${PORT:8082}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL:}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:false}

apis:
  openagenda:
    base-url: ${OPENAGENDA_BASE_URL:https://api.openagenda.com/v2}
    public-key: ${OPENAGENDA_PUBLIC_KEY:}
    agenda-uid: ${OPENAGENDA_AGENDA_UID:}

ga4:
  measurementId: ${GA4_MEASUREMENT_ID:}
  apiSecret: ${GA4_API_SECRET:}

unsplash:
  accessKey: ${UNSPLASH_ACCESS_KEY:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.cultureradar: INFO
    org.springframework.web: INFO

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
